export const LOGIN_SUCCESS = 'login_success'
export const ALTER_LOGIN_SUCCESS = 'alter_login_success'
export const LOGIN_HOMOLOG_SUCCESS = 'login_homolog_success'
export const LOGOUT_SUCCESS = 'logout_success'
export const FORGOT_SUCCESS = 'forgot_success'
export const FORGOT_TOKEN_SUCCESS = 'forgot_token_success'
export const LOCATION_SUCCESS = 'location_success'
export const DEVICE_ID_SUCCESS = 'device_id_success'
export const CNH_SUCCESS = 'cnh_success'
export const FREIGHT_PREFERENCES_SUCCESS = 'preferences_success'
export const FREIGHT_WISH_SUCCESS = 'wish_success'
export const GET_TRUCK_BODIES_SUCCESS = 'get_truck_bodies_success'
export const GET_VEHICLES_SUCCESS = 'get_vehicles_success'
export const ON_LOAD_CNH_TYPES = 'on_load_cnh_types'
export const ON_LOAD_VEHICLE_TYPES = 'on_load_vehicle_types'
export const ON_LOAD_TRUCK_BODY_TYPES = 'on_load_truck_body_types'
export const ON_LOAD_FUEL_TYPES = 'on_load_fuel_types'
export const ON_LOAD_REGIONS = 'on_load_regions'
export const ON_LOAD_STATUS_MONITORING = 'on_load_status_monitoring'
export const ON_LOAD_STATUS_REASON_MONITORING =
    'on_load_status_reason_monitoring'
export const ON_LOAD_TRACKER_TYPES = 'on_load_tracker_types'
export const ON_LOAD_OCCURRENCE_TYPES = 'on_load_occurrence_types'
export const ON_LOAD_SACREPORT_TYPES = 'on_load_sacreport_types'
export const ON_LOAD_OCCURRENCE_TYPES_GO = 'on_load_occurrence_types_go'
export const OWNERS_VEHICLES = 'owners_vehicles'
export const RESPONSIBLE_FREIGHT_SUCCESS = 'responsible_freight_success'
export const PREVENTIVE_MONITORING_SUCCESS = 'preventive_monitoring_success'
export const IS_TRAVEL = 'is_travel'

export const SET_SHIPPING_COMPANIES = 'set_shipping_companies'
export const SET_SHIPPING_COMPANIE = 'set_shipping_companie'

export const ON_LOAD_JOURNEYS_OF_OPERATOR_TYPES = 'jorneys_of_operator_types'
export const ETA_CALCULATION = 'eta_calculation'

export const CURRENT_TRIP = 'current_trip'

export const ON_LOAD_JOURNEYS_OF_OPERATOR = 'jorneys_of_operator'
    //export const ETA_CALCULATION = 'eta_calculation'
